version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parachutes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - POSTGRESQL=postgresql+asyncpg://user:password@postgres:5432/parachutes
      - REDIS=redis://redis_cache:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - STORAGE_BUCKET=parachutes
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio

volumes:
  postgres_data:
  minio_data:
