apiVersion: batch/v1
kind: CronJob
metadata:
  name: invocation-exporter
spec:
  schedule: "50 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.invocationExporter.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: csv-export
            image: {{ .Values.invocationExporter.image }}
            imagePullPolicy: Always
            command: ["/bin/sh", "/scripts/export.sh"]
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-access-key
            - name: AWS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: endpoint-url
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: aws-region
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: bucket
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: hostname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            volumeMounts:
            - name: export-script
              mountPath: /scripts
            - name: tmpdir
              mountPath: /tmp
          volumes:
          - name: export-script
            configMap:
              name: invocation-export-code
              defaultMode: 0755
          - name: tmpdir
            emptyDir: {}
          restartPolicy: OnFailure
