apiVersion: v1
kind: Service
metadata:
  name: graval
  labels:
    {{- include "graval.labels" . | nindent 4 }}
spec:
  type: NodePort
  internalTrafficPolicy: Local
  externalTrafficPolicy: Local
  ports:
    - nodePort: {{ .Values.graval.service.nodePort }}
      port: {{ .Values.graval.service.port }}
      targetPort: {{ .Values.graval.service.targetPort }}
      name: validator-graval
  selector:
    {{- include "graval.labels" . | nindent 4 }}
