apiVersion: v1
kind: Service
metadata:
  name: pgproxy
  labels:
    {{- include "pgproxy.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.pgproxy.service.port }}
      targetPort: pgproxy
      protocol: TCP
      name: pgproxy
  selector:
    {{- include "pgproxy.labels" . | nindent 4 }}
