apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgproxy-network-policy
  labels:
    {{- include "pgproxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pgproxy.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              db-access: "true"
      ports:
        - protocol: TCP
          port: {{ .Values.pgproxy.service.port }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
