apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: registry
      protocol: TCP
      name: registry
  selector:
    {{- include "registry.labels" . | nindent 4 }}
