apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry.labels" . | nindent 8 }}
    spec:
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: registry
          image: "{{ .Values.registry.image }}"
          imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
          env:
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: aws-region
            - name: REGISTRY_STORAGE_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: bucket
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key-id
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-access-key
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: endpoint-url
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: password
            - name: REGISTRY_STORAGE_REDIRECT_DISABLE
              value: "{{ .Values.registry.config.redirectDisable }}"
          ports:
            - name: registry
              containerPort: {{ .Values.registry.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
