all:
  hosts:
    chutes-prod-0:
      ansible_host: 1.2.3.4
      external_ip: 1.2.3.4
      wireguard_ip: 192.168.0.1
      ansible_user: ubuntu
      user: jdurbin
      gpu_enabled: false
      is_primary: true
      ssh_key: "ssh-rsa A... foo@bar"
    chutes-prod-gpu-0:
      ansible_host: 4.5.6.7
      external_ip: 4.5.6.7
      wireguard_ip: 192.168.0.2
      ansible_user: ubuntu
      user: jdurbin
      gpu_enabled: true
      is_primary: false
      ssh_key: "ssh-rsa A.. foo@bar"
