all:
  hosts:
    cpu-node-0:
      ansible_host: 0.1.2.3
      external_ip: 0.1.2.3
      ansible_user: ubuntu
      user: billybob
      gpu_enabled: true
      ssh_key: "ssh-rsa AAAA... billybob@machine"
      validator: "5DCJTfVx3ReNyxW3SgQEKFgvXFuqnK3BNW1vMhTQK4jdZbV4"
    gpu-node-0:
      ansible_host: 4.5.6.7
      external_ip: 4.5.6.7
      ansible_user: ubuntu
      user: billybob
      gpu_enabled: true
      ssh_key: "ssh-rsa AAAA... billybob@machine"
      validator: "5DCJTfVx3ReNyxW3SgQEKFgvXFuqnK3BNW1vMhTQK4jdZbV4"

  children:
    k8s_cluster:
      children:
        primary:
          hosts:
            cpu-node-0:
              ansible_host: 0.1.2.3
        secondary: {}
        workers:
          hosts:
            gpu-node-0:
              ansible_host: 1.2.3.4
